### ISSUE TITLE
Reporting attempts stop after 2-3 hours of traffic

### ISSUE THREAD

**Issue by parker-edwards** [lightstep/lightstep-tracer-csharp#29]
Reported from user:

It appears transport attempts stop after a service has been alive for 2-3 hours running > 100 ops/second. No logs in host or Satellites to suggest reporting attempts are being made unsuccessfully.

**Comment by austinlparker** [comment]
After spending some time investigating this, what seems to be happening is that after some amount of time the `HttpClient` gets into a persistent failed state after receiving a 413 HTTP response from a satellite. I'm going to see if I can figure out what triggers the error but I should be able to get a temporary fix out today.

**Comment by austinlparker** [comment]
See #31 for the temporary fix.

**Comment by austinlparker** [comment]
I tried to reproduce this locally over the past day or so with no success (I ran approximately 100 ops/sec for about 20 hours straight) and never got a drop or reset on the client. I'm going to close this issue as I can't reproduce it any more.
