### ISSUE TITLE
System.OverflowException when creating spans from invalid parent IDs

### ISSUE THREAD

**Issue by parker-edwards** [lightstep/lightstep-tracer-csharp#50]
When the tracer builds a span off of an invalid parent span ID we get an exception when LightStep.Collector.Span.MakeSpanFromSpanData() calls System.Convert.ToUInt64() resulting in a System.OverflowException which is fatal to the host app.

**Comment by austinlparker** [comment]
If the parent ID doesn't exist we don't try to do a conversion; we do attempt to convert the duration via a call to `ToUInt64`. Is this a span that doesn't have a duration somehow?

Either way, I believe we can make the tracer more resilient to conversion failures by dropping bad spans and reporting the drop.
