### ISSUE TITLE
Tags/Logs should allow Object values and interpret them as JSON.

### ISSUE THREAD

**Issue by austinlparker** [lightstep/lightstep-tracer-csharp#64]
In an effort to comport with our other tracers, we should accept object values and transform them into JSON for tags and log values.

**Comment by BhuvanB** [comment]
Does it really make sense to support objects for tags? LS queries only support direct matches. Bringing in serialization issues like ordering of keys seems like needless complications.

**Comment by austinlparker** [comment]
Not gonna wind up working on this one I think!
