### ISSUE TITLE
All await calls block the current thread when executed syncronously

### ISSUE THREAD

**Issue by MikeGoldsmith** [lightstep/lightstep-tracer-csharp#79]
When executing an Task based method in a synchronous manner (eg `function().Result`), the current thread's context is used when resuming. However, this can cause issues in web and desktop applications if the UI thread is used to execute these methods and may result in deadlocks.

To prevent this from happening, asynchronous should use `configureAwait(false)` to not require the original context when resuming after calling await.

**Comment by austinlparker** [comment]
closed by #91
