### ISSUE TITLE
Please provide a `net461` or `net472` project target to match `netstandard2.0` preprocessor

### ISSUE THREAD

**Issue by hotchkj** [lightstep/lightstep-tracer-csharp#96]
We recently hit a surprising bit of behaviour by MSBuild related to this project. It turns out that the [order of framework precedence](https://nugettoolsdev.azurewebsites.net/4.4.2/framework-precedence?framework=net472&exludedIdentifiers=) means that any NET Framework compile ends up pulling the `net45` target, despite `netstandard2.0` being later, offering more features, less bugs, etc.

In particular this means any `net45` specific behaviour that turns out to be a problem simply due to age of the associated language feature (more relevant to OpenTracing than here) is really hard to avoid.

It would be ideal if the preprocessor usage in the tracer assembly used the NET Standard 2.0 approach (wherever that is necessary) also for a later `netxxx` target (which will avoid surprises like this).

In theory `net461` matches `netstandard2.0` in API surface area, but given the Microsoft fine print:
> there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

This could just be `net472` for safety's sake.

**Comment by austinlparker** [comment]
I've got a change ready to go that would bump the min version up to net472 in #99, would something like that work?

**Comment by hotchkj** [comment]
Awesome news @austinlparker - I hadn't expected the drop of `net45`, this is excellent, thank you! I added a couple of comments on the PR, hope it's helpful.

**Comment by austinlparker** [comment]
Thanks, it was. I'm hopeful we can get this out - there's some pretty significant performance improvements I noticed by dropping `net45` and updating dependencies, so I think it's worth it for most people...
